# format and mount ebs volume
#
---
  - hosts: web1
    become: true
    vars:
        mount_src: /dev/xvdc
        mount_path: /backup
    tasks:
      - name: Get list of mounted devices
        set_fact:
          mounted_devices: "{{ ansible_mounts|json_query('[].device') }}"
      - name: "Create xfs partition"
        parted:
          device: "{{ mount_src }}"
          state: present
          unit: GB
          number: 1
        register: sdb_info
        when:  mount_src not in mounted_devices
      - name: "Create the filesystem"
        filesystem: 
          fstype: xfs
          dev: "{{ mount_src }}" 
        when:  mount_src not in mounted_devices
      - name: "Mount backup drive"
        mount:
          path: "{{ mount_path }}" 
          fstype: xfs
          src: "{{ mount_src }}" 
          state: mounted
          opts: defaults,nofail
          passno: 2
        when:  mount_src not in mounted_devices
