all:
  children:
    loadbalancers:
      hosts:
        lb1:
          ansible_host: web-traffic-lb-1153026098.us-west-2.elb.amazonaws.com
    local:
      hosts:
        ansible_connection=local: {}
        control: {}
    ungrouped: {}
    webservers:
      hosts:
        web1:
          ansible_host: 44.237.94.143
        web2:
          ansible_host: 52.13.124.109
